-- File: drop.sql  
-- Drops the the DB schema
-- Author: 
--
SET ECHO ON
DROP TABLE Product CASCADE CONSTRAINTS;
DROP TABLE Orders CASCADE CONSTRAINTS;
DROP TABLE Store CASCADE CONSTRAINTS;
DROP TABLE Workers CASCADE CONSTRAINTS;
DROP TABLE CD CASCADE CONSTRAINTS;
DROP TABLE CD_genre CASCADE CONSTRAINTS;
DROP TABLE CD_artist CASCADE CONSTRAINTS;
DROP TABLE SellsA CASCADE CONSTRAINTS;
DROP TABLE Contains CASCADE CONSTRAINTS;
SET ECHO OFF